name: MeanBeatz
favicon: null
layout_spectrum: 0.15364
typography_spectrum: 0.23684
title: MeanBeatz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-53769172-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3beac'
    - '#0b0b13'
    - '#545e81'
    - '#6f9efa'
    - '#bbeafe'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
