name: MeanBeatz
favicon: null
layout_spectrum: 0.54242
typography_spectrum: 0.35244
title: MeanBeatz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-53769172-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#007dbb'
    - '#b18057'
    - '#eebeb0'
  brandStrength: 0.9320546346716583
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
