name: MeanBeatz
favicon: null
layout_spectrum: 0.93216
typography_spectrum: 0.23684
title: MeanBeatz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-53769172-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#efefe5'
    - '#9d9b82'
    - '#71705b'
    - '#35362e'
  brandStrength: 0.9320546346716583
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
