name: MeanBeatz
favicon: null
layout_spectrum: 0.54242
typography_spectrum: 0.35244
title: MeanBeatz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#005c88'
    - '#dbb699'
    - '#714b38'
  brandStrength: 0.9320546346716583
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
